-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

vim.keymap.del("n", "<leader>gs")
vim.keymap.del("n", "<leader>gL")
vim.keymap.del("n", "<leader>gG")
vim.keymap.del("n", "<leader>gY")
vim.keymap.del("n", "<leader>l")
vim.keymap.del("n", "<leader>L")
vim.keymap.del("n", "<leader>K")
vim.keymap.del("n", "<leader>E")
vim.keymap.del("n", "<leader>`")
vim.keymap.del("n", "<leader>D")
-- vim.keymap.del("n", "<leader>gc")
-- vim.keymap.del("n", "<leader>K")
-- vim.keymap.del("n", "<leader>L")
-- vim.keymap.del("n", "<leader>E")
-- vim.keymap.del("n", "<leader>e")
-- vim.keymap.del("n", "<leader>?")
-- vim.keymap.del("n", "<leader>:")
-- vim.keymap.del("n", "<leader><tab>l")
-- vim.keymap.del("n", "<leader><tab>o")
-- vim.keymap.del("n", "<leader><tab>f")
-- vim.keymap.del("n", "<leader><tab><tab>")
-- vim.keymap.del("n", "<leader><tab>]")
-- vim.keymap.del("n", "<leader><tab>d")
-- vim.keymap.del("n", "<leader><tab>[")
-- vim.keymap.del("n", "<leader>fe")
-- vim.keymap.del("n", "<leader>fE")
-- vim.keymap.del("n", "<leader>fR")
-- vim.keymap.del("n", "<leader>fF")
-- vim.keymap.del("n", "<leader>fB")
-- vim.keymap.del("n", "<leader>/")
-- vim.keymap.del("n", "<leader>sg")
-- vim.keymap.del("n", "<leader>sG")
-- vim.keymap.del("n", "<leader>gB")
-- vim.keymap.del("n", "<leader>gf")
